### ISSUE TITLE
tasks point to wrong gitlab project

### ISSUE THREAD

**Issue by Fxr12042** [OSINTer-Platform/ansible#2]
the repositories are being cloned from gitlab.com/osinter instead of github.com/OSINTer-Platform. The latter contains new files (for instance, the initialize app for elasticsearch).

**Comment by bertmad3400** [comment]
Hi @Fxr12042!

Awesome to see you getting involved in the project! Unfortunately, this repo is rather outdated and no longer maintained (and should probably have been archived a long time ago), and as such you will probably find multiple places where the code isn't working properly (see the notice I have just added to the README for a longer explanation). I do however strongly encourage user/community involvement in the project as a whole, and as such I have gone ahead and fixed this issue in https://github.com/OSINTer-Platform/ansible/commit/aa32b90dea6c10f41ce6c06bc2146b2b356e3c22.

Feel free to open issues and especially PR's on any part of the project (including this repo), if you feel something is missing.

Bertram
